### ISSUE TITLE
Clean up odd traceback when mistyping the qualifier not_to

### ISSUE THREAD

**Issue by jmvrbanac** [jmvrbanac/Specter#45]
If you accidentally use ```to_not``` instead of ```not_to```, you get the correct error, but it then pushes out a second traceback that doesn't make much sense. Should be cleaned up.

```
      --> 40:         expect(inst).to_not.be_none()
        ------------------
        - Error | AttributeError: 'ExpectAssert' object has no attribute 'to_not'
Traceback (most recent call last):
  File ".tox/py27/bin/specter", line 9, in <module>
    load_entry_point('Specter==0.1.15', 'console_scripts', 'specter')()
  File "/home/john/Repositories/github/Rift/.tox/py27/lib/python2.7/site-packages/specter/runner.py", line 163, in activate
    runner.run(args)
  File "/home/john/Repositories/github/Rift/.tox/py27/lib/python2.7/site-packages/specter/runner.py", line 137, in run
    parallel_manager=self.parallel_manager)
  File "/home/john/Repositories/github/Rift/.tox/py27/lib/python2.7/site-packages/specter/spec.py", line 316, in execute
    self.standard_execution(select_metadata)
  File "/home/john/Repositories/github/Rift/.tox/py27/lib/python2.7/site-packages/specter/spec.py", line 294, in standard_execution
    self.top_parent.dispatch(TestEvent(case))
  File "/home/john/Repositories/github/Rift/.tox/py27/lib/python2.7/site-packages/pyevents/manager.py", line 58, in dispatch
    listener.callback(event)
  File "/home/john/Repositories/github/Rift/.tox/py27/lib/python2.7/site-packages/specter/reporting/console.py", line 93, in event_received
    print_expects(test_case, level)
  File "/home/john/Repositories/github/Rift/.tox/py27/lib/python2.7/site-packages/specter/reporting/console.py", line 219, in print_expects
    expect_msg = u'{mark} {msg}'.format(mark=mark, msg=expect)
  File "/home/john/Repositories/github/Rift/.tox/py27/lib/python2.7/site-packages/specter/expect.py", line 109, in __str__
    action_list[-1] = self.expected_src_param or str(self.expected)
AttributeError: 'ExpectAssert' object has no attribute 'expected'

```

**Comment by jmvrbanac** [comment]
Cannot replicate as of 0.2.0. Closing for now.
